const Questions = [
    // Easy Questions
    {
        id: 0,
        question: "What is the rarest M&M color?",
        option1: "Red",
        option2: "Yellow",
        option3: "Brown",
        option4:"Blue",
        answer: "Brown",
    },
    {
        id: 1,
        question: "In a website browser address bar, what does “www” stand for?",
        option1: "World Wide Web",
        option2: "Whole Wide Web",
        option3: "Web World Wide",
        option4:"Wide Web World",
        answer: "World Wide Web",
    },
    {
        id: 2,
        question: "In what year were the first Air Jordan sneakers released?",
        option1: "1989",
        option2: "1990",
        option3: "1995",
        option4:"1984",
        answer: "1984",
    },
    {
        id: 3,
        question: "In a bingo game, which number is represented by the phrase “two little ducks”?",
        option1: "33",
        option2: "22",
        option3: "23",
        option4:"44",
        answer: "22",
    },
    {
        id: 4,
        question: "According to Greek mythology, who was the first woman on earth?",
        option1: "Hera",
        option2: "Aphrodite",
        option3: "Pandora",
        option4:"Athena",
        answer: "Pandora",
    },
    {
        id: 5,
        question: "Which African country was formerly known as Abyssinia?",
        option1: "Ethiopia",
        option2: "Sudan",
        option3: "Kenya",
        option4:"Uganda",
        answer: "Ethiopia",
    },
    {
        id: 6,
        question: "Which author wrote the ‘Winnie-the-Pooh’ books?",
        option1: "A. A. Milne",
        option2: "George R.R. Martin",
        option3: "Mark Twain",
        option4:"J.K. Rowling",
        answer: "A. A. Milne",
    },
    {
        id: 7,
        question: "Which country consumes the most chocolate per capita?",
        option1: "Italy",
        option2: "Germany",
        option3: "America",
        option4:"Switzerland",
        answer: "Switzerland",
    },
    {
        id: 8,
        question: "Which two U.S. states don’t observe Daylight Saving Time?",
        option1: "Hawaii and Maine",
        option2: "Arizona and Alaska",
        option3: "Arizona and Hawaii",
        option4:"Alaska and Hawaii",
        answer: "Arizona and Hawaii",
    },
    {
        id: 9,
        question: "What is the loudest animal on Earth?",
        option1: "The Pistol Shrimp",
        option2: "The Rooster",
        option3: "The Dolphin",
        option4:"The Sperm Whale",
        answer: "The Sperm Whale",
    },
    {
        id: 10,
        question: "What is the tiny piece at the end of a shoelace called?",
        option1: "A lace tip",
        option2: "A lace cover",
        option3: "A shoe string",
        option4:"An aglet",
        answer: "An aglet",
    },
    {
        id: 11,
        question: "Which of Shakespeare’s plays is the longest?",
        option1: "Hamlet",
        option2: "Macbeth",
        option3: "Romeo and Juliet",
        option4:"Othello",
        answer: "Hamlet",
    },
    {
        id: 12,
        question: "Outside which New York building was John Lennon killed?",
        option1: "Chrysler Building",
        option2: "The Dakota Building",
        option3: "The Empire State Building",
        option4:"Rockefeller Plaza",
        answer: "The Dakota Building",
    },
    {
        id: 13,
        question: "What is the tallest breed of dog in the world?",
        option1: "The Greyhound",
        option2: "The Mastiff",
        option3: "The Great Dane",
        option4:"Newfoundland",
        answer: "The Great Dane",
    },
    {
        id: 14,
        question: "What is the softest mineral in the world?",
        option1: "Gypsum",
        option2: "Calcite",
        option3: "Fluorite",
        option4:"Talc",
        answer: "Talc",
    },
    {
        id: 15,
        question: "How many ribs are in a human body?",
        option1: "24",
        option2: "26",
        option3: "20",
        option4:"22",
        answer: "24",
    },
    {
        id: 16,
        question: "What is the world’s biggest island?",
        option1: "Largeland",
        option2: "Greenland",
        option3: "Madagascar",
        option4:"Alaska",
        answer: "Greenland",
    },
    {
        id: 17,
        question: "Which country is known as the Land of White Elephant?",
        option1: "Indonesia",
        option2: "Laos",
        option3: "Thailand",
        option4:"China",
        answer: "Thailand",
    },
    {
        id: 18,
        question: "What is the smallest ocean in the world?",
        option1: "Pacific",
        option2: "Red",
        option3: "Atlantic",
        option4:"Arctic",
        answer: "Arctic",
    },
    {
        id: 19,
        question: "What color eyes do most humans have?",
        option1: "Brown",
        option2: "Green",
        option3: "Hazel",
        option4:"Blue",
        answer: "Brown",
    },
    {
        id: 20,
        question: "What is the largest type of deer?",
        option1: "Elk",
        option2: "Moose",
        option3: "Bambi",
        option4:"Giraffe",
        answer: "Moose",
    },
    {
        id: 21,
        question: "Which Disney film features the song ‘When You Wish Upon a Star’?",
        option1: "Beauty and the Beast",
        option2: "Hercules",
        option3: "Pinocchio",
        option4:"Mulan",
        answer: "Pinocchio",
    },
    {
        id: 22,
        question: "What is the name of the Earth’s largest ocean?",
        option1: "Arctic",
        option2: "Red",
        option3: "Atlantic",
        option4:"Pacific",
        answer: "Pacific",
    },
    {
        id: 23,
        question: "When Michael Jordan played for the Chicago Bulls, how many NBA Championships did he win?",
        option1: "6",
        option2: "4",
        option3: "7",
        option4:"5",
        answer: "6",
    },
    {
        id: 24,
        question: "What country won the very first FIFA World Cup in 1930?",
        option1: "Germany",
        option2: "Uruguay",
        option3: "Spain",
        option4:"Italy",
        answer: "Uruguay",
    },
    {
        id: 25,
        question: "What is often seen as the smallest unit of memory?",
        option1: "ittybyte",
        option2: "megabyte",
        option3: "kilobyte",
        option4:"gigabyte",
        answer: "kilobyte",
    },
    {
        id: 26,
        question: "Which planet is the hottest in the solar system?",
        option1: "Mercury",
        option2: "Mars",
        option3: "Sun",
        option4:"Venus",
        answer: "Venus",
    },
    {
        id: 27,
        question: "Which country produces the most coffee in the world?",
        option1: "Brazil",
        option2: "Germany",
        option3: "America",
        option4:"Columbia",
        answer: "Brazil",
    },
    {
        id: 28,
        question: "What is the common name for dried plums?",
        option1: "Rasins",
        option2: "Prunes",
        option3: "Praisins",
        option4:"Runes",
        answer: "Prunes",
    },
    {
        id: 29,
        question: "What does BMW stand for (in English)?",
        option1: "Buy More Works",
        option2: "British Motor Works",
        option3: "Big Money Waster",
        option4:"Bavarian Motor Works",
        answer: "Bavarian Motor Works",
    },
    {
        id: 30,
        question: "Which two countries share the longest international border?",
        option1: "Argentina and Chile",
        option2: "USA and Mexico",
        option3: "Canada and the USA",
        option4:"China and Mongolia",
        answer: "Canada and the USA",
    },
    {
        id: 31,
        question: "What is the smallest country in the world?",
        option1: "Italy",
        option2: "Monaco",
        option3: "Rome",
        option4:"Vatican City",
        answer: "Vatican City",
    },
    {
        id: 32,
        question: "Which bone are babies born without?",
        option1: "Knee cap",
        option2: "Funny bone",
        option3: "Back bone",
        option4:"Vertebrae",
        answer: "Knee cap",
    },
    {
        id: 33,
        question: "Which name is rapper Sean Combs better known by?",
        option1: "Tupac",
        option2: "P. Diddy",
        option3: "Puff Daddy",
        option4:"Puffy",
        answer: "P. Diddy",
    },
    {
        id: 34,
        question: "Which British girl group had a member by the name of Mel B?",
        option1: "All Saints",
        option2: "Addictive",
        option3: "Atomic Kitten",
        option4:"Spice Girls",
        answer: "Spice Girls",
    },
    {
        id: 35,
        question: "How many hearts does an octopus have?",
        option1: "3",
        option2: "2",
        option3: "5",
        option4:"4",
        answer: "3",
    },
    {
        id: 36,
        question: "How many eyes does a bee have?",
        option1: "8",
        option2: "5",
        option3: "6",
        option4:"4",
        answer: "5",
    },
    {
        id: 37,
        question: "What was the name of the rock band formed by Jimmy Page?",
        option1: "AC/DC",
        option2: "Red Hot Chili Peppers",
        option3: "Led Zeppelin",
        option4:"Nirvana",
        answer: "Led Zeppelin",
    },
    {
        id: 38,
        question: "Which mammal has no vocal cords?",
        option1: "Walrus",
        option2: "Rhino",
        option3: "Zebra",
        option4:"Giraffe",
        answer: "Giraffe",
    },
    {
        id: 39,
        question: "What type of music has been shown to help plants grow better and faster?",
        option1: "Classical",
        option2: "Reggae",
        option3: "Soul",
        option4:"R&B",
        answer: "Classical",
    },
    {
        id: 40,
        question: "Power outages in the US are mostly caused by what?",
        option1: "Car Accidents",
        option2: "Short Circuits",
        option3: "Lightning",
        option4:"Squirrels",
        answer: "Squirrels",
    },
    {
        id: 41,
        question: "What was the first state?",
        option1: "Pennsylvania",
        option2: "Delaware",
        option3: "New Jersey",
        option4:"Georgia",
        answer: "Delaware",
    },
    {
        id: 42,
        question: "What is the painting ‘La Gioconda’ more usually known as?",
        option1: "The Starry Night",
        option2: "Girl with a Pearl Earring",
        option3: "Mona Lisa",
        option4:"The Persistence of Memory",
        answer: "Mona Lisa",
    },
    {
        id: 43,
        question: "Water has a pH level of around?",
        option1: "3",
        option2: "5",
        option3: "0",
        option4:"7",
        answer: "7",
    },
    {
        id: 44,
        question: "What’s the hardest rock?",
        option1: "Diamond",
        option2: "Obsidian",
        option3: "Onyx",
        option4:"Crack",
        answer: "Diamond",
    },
    {
        id: 45,
        question: "What is the national dish of Spain?",
        option1: "Gazpacho",
        option2: "Paella",
        option3: "Jamon",
        option4:"Fideuà",
        answer: "Paella",
    },
    {
        id: 46,
        question: "Which horoscope sign has a crab?",
        option1: "Libra",
        option2: "Capricorn",
        option3: "Cancer",
        option4:"Taurus",
        answer: "Cancer",
    },
    {
        id: 47,
        question: "What color is Absinthe?",
        option1: "Yellow",
        option2: "Red",
        option3: "Blue",
        option4:"Green",
        answer: "Green",
    },
    {
        id: 48,
        question: "The Statue of Liberty was given to the US by which country?",
        option1: "France",
        option2: "Germany",
        option3: "Canada",
        option4:"Mexico",
        answer: "France",
    },
    {
        id: 49,
        question: "Where is the Sea of Tranquility located?",
        option1: "Malta",
        option2: "Belize",
        option3: "Madagascar",
        option4:"The Moon",
        answer: "The Moon",
    }
]

const MediumQuestions = [
    {
        id: 0,
        question: "Who is the Pokemon Anime’s main character?",
        option1: "Ash",
        option2: "Brock",
        option3: "Misty",
        option4:"Gary",
        answer: "Ash",
    },
    {
        id: 1,
        question: "In the anime series 'Full Metal Alchemist', what do Alchemists consider the greatest taboo?",
        option1: "Cannibalism",
        option2: "Human Transmutation",
        option3: "Mutiny",
        option4:"Revolution",
        answer: "Human Transmutation",
    },
    {
        id: 2,
        question: "What year was 'JoJo's Bizarre Adventure: Phantom Blood' first released?",
        option1: "2000",
        option2: "1990",
        option3: "1987",
        option4:"1992",
        answer: "1987",
    },
    {
        id: 3,
        question: "Who created the animated movie 'Spirited Away' (2001)?",
        option1: "Osamu Tezuka",
        option2: "Noburō Ōfuji",
        option3: "Mamoru Oshii",
        option4:"Hayao Miyazaki",
        answer: "Hayao Miyazaki",
    },
    {
        id: 4,
        question: "What sport is being played in the Anime Eyeshield 21?",
        option1: "American Football",
        option2: "Soccer",
        option3: "Baseball",
        option4:"Volleyball",
        answer: "American Football",
    },
    {
        id: 5,
        question: "Who is the main character with yellow hair in the anime Naruto?",
        option1: "Sasuke",
        option2: "Naruto",
        option3: "Rock Lee",
        option4:"Bee",
        answer: "Naruto",
    },
    {
        id: 6,
        question: "What is the last name of Edward and Alphonse in the Fullmetal Alchemist series?",
        option1: "Uchiha",
        option2: "Son",
        option3: "Elric",
        option4:"Levi",
        answer: "Elric",
    },
    {
        id: 7,
        question: "In Dragon Ball Z, who was the first character to go Super Saiyan 2?",
        option1: "Krillin",
        option2: "vegeta",
        option3: "Goku",
        option4:"Gohan",
        answer: "Gohan",
    },
    {
        id: 8,
        question: "What is the name of the corgi in Cowboy Bebop?",
        option1: "Einstein",
        option2: "Daisy",
        option3: "Doge",
        option4: "Elly",
        answer: "Einstein",
    },
    {
        id: 9,
        question: "What is the name of the main character of the anime 'One-Punch Man'?",
        option1: "Genos",
        option2: "Saitama",
        option3: "Garou",
        option4:"Crablante",
        answer: "Saitama",
    },
    {
        id: 10,
        question: "Which anime heavily features music from the genre 'Eurobeat'?",
        option1: "Yu Yu Hakasho",
        option2: "Cowboy Bebop",
        option3: "Initial D",
        option4:"Akira",
        answer: "Initial D",
    },
    {
        id: 11,
        question: "What was Ash Ketchum's second Pokemon?",
        option1: "Bulbasaur",
        option2: "Pidgeotto",
        option3: "Pikachu",
        option4:"Caterpie",
        answer: "Caterpie",
    },
    {
        id: 12,
        question: "What year did 'Attack on Titan' Season 2 begin airing?",
        option1: "2017",
        option2: "2018",
        option3: "2016",
        option4:"2015",
        answer: "2017",
    },
    {
        id: 13,
        question: "In the 'Dragon Ball' franchise, what is the name of Goku's brother?",
        option1: "Vegeta",
        option2: "Raditz",
        option3: "Krillin",
        option4:"Broly",
        answer: "Raditz",
    },
    {
        id: 14,
        question: "The two main characters of 'No Game No Life', Sora and Shiro, together go by what name?",
        option1: "Void",
        option2: "X",
        option3: "Blank",
        option4:"Zero",
        answer: "Blank",
    },
    {
        id: 15,
        question: "In 'Hunter x Hunter', what are members in Killua's family known for being?",
        option1: "Trainer's",
        option2: "Butler's",
        option3: "Hero's",
        option4:"Assassin's",
        answer: "Assassin's",
    },
    {
        id: 16,
        question: "In Digimon, what is the Japanese name for the final evolutionary stage?",
        option1: "Ultimate",
        option2: "Final",
        option3: "Ultra",
        option4:"Mega",
        answer: "Ultimate",
    },
    {
        id: 17,
        question: "What year did 'Attack on Titan' first air?",
        option1: "2011",
        option2: "2013",
        option3: "2012",
        option4:"2010",
        answer: "2013",
    },
    {
        id: 18,
        question: "In 'Attack on Titan', What has been terrorizing humans?",
        option1: "Ants",
        option2: "Mutants",
        option3: "Titans",
        option4:"Gods",
        answer: "Titans",
    },
    {
        id: 19,
        question: "In 'Attack on Titan', What is the outermost wall protecting the humans called?",
        option1: "Wall Sina",
        option2: "Wall Titan",
        option3: "Wall Rose",
        option4:"Wall Maria",
        answer: "Wall Maria",
    },
    {
        id: 20,
        question: "In 'Attack on Titan', Which branch of the military protects the Royal Family?",
        option1: "Military Police Brigade",
        option2: "Scout Regiment",
        option3: "Secret Service",
        option4:"Garrison Regiment",
        answer: "Military Police Brigade",
    },
    {
        id: 21,
        question: "In 'Attack on Titan', Which family member does Eren watch get eaten by a Titan?",
        option1: "Father",
        option2: "Mother",
        option3: "Sister",
        option4:"Brother",
        answer: "Mother",
    },
    {
        id: 22,
        question: "In 'Attack on Titan', What is the second outermost wall protecting the humans called?",
        option1: "Wall Sina",
        option2: "Wall Titan",
        option3: "Wall Rose",
        option4:"Wall Maria",
        answer: "Wall Rose",
    },
    {
        id: 23,
        question: "In 'Attack on Titan', What is the name of innermost wall?",
        option1: "Wall Sina",
        option2: "Wall Titan",
        option3: "Wall Rose",
        option4:"Wall Maria",
        answer: "Wall Sina",
    },
    {
        id: 24,
        question: "In 'Attack on Titan', Who is Eren's adopted sister?",
        option1: "Hange Zoe",
        option2: "Sasha Braus",
        option3: "Annie Leonhart",
        option4:"Mikasa Ackerman",
        answer: "Mikasa Ackerman",
    },
    {
        id: 25,
        question: "In 'Attack on Titan', Who is the first human shown to be a Titan?",
        option1: "Eren",
        option2: "Annie",
        option3: "Armin",
        option4:"Mikasa",
        answer: "Eren",
    },
    {
        id: 26,
        question: "In 'Attack on Titan', Where does the Colossal Titan knock a hole in Wall Maria?",
        option1: "Calaneth",
        option2: "Shiganshina",
        option3: "Trost",
        option4:"Utopia",
        answer: "Shiganshina",
    },
    {
        id: 27,
        question: "In 'Attack on Titan', Who is ranked first in the Southern Division in the 104th Training Corps?",
        option1: "Armin",
        option2: "Annie",
        option3: "Mikasa",
        option4:"Eren",
        answer: "Mikasa",
    },
    {
        id: 28,
        question: "In 'Attack on Titan', Which branch of the military tries to reclaim land from Titans?",
        option1: "Titan Hunters",
        option2: "Military Police Brigade",
        option3: "Garrison Regiment",
        option4:"Scout Regiment",
        answer: "Scout Regiment",
    },
    {
        id: 29,
        question: "In 'Attack on Titan', What's the equipment used for grappling called?",
        option1: "3D Maneuver Gear",
        option2: "Grappling Gear",
        option3: "Combat Equipment",
        option4:"Jumping Device",
        answer: "3D Maneuver Gear",
    },
    {
        id: 30,
        question: "In 'Attack on Titan', Who is considered 'humanity's strongest soldier?'",
        option1: "Eren",
        option2: "Levi",
        option3: "Mikasa",
        option4:"Marco",
        answer: "Levi",
    },
    {
        id: 31,
        question: "In 'Attack on Titan', Who is the Female Titan?",
        option1: "Mikasa",
        option2: "Sasha",
        option3: "Annie",
        option4:"Dina",
        answer: "Annie",
    },
    {
        id: 32,
        question: "In 'Attack on Titan', Which branch of the military guards the walls and the general population?",
        option1: "Wall Defense Force",
        option2: "Military Police Brigade",
        option3: "Scout Regiment",
        option4:"Garrison Regiment",
        answer: "Garrison Regiment",
    },
    {
        id: 33,
        question: "In 'Attack on Titan', Who is the commander of the Scout Regiment?",
        option1: "Erwin Smith",
        option2: "Levi",
        option3: "Jean Kirschtein",
        option4:"Eren",
        answer: "Erwin Smith",
    },
    {
        id: 34,
        question: "In 'Attack on Titan', Who is Eren's best friend?",
        option1: "Armin Arlert",
        option2: "Reiner Braun",
        option3: "Jean Kirschtein",
        option4:"Sasha Braus",
        answer: "Armin Arlert",
    },
    {
        id: 35,
        question: "In 'Attack on Titan', What kind of Titan is Eren?",
        option1: "Armored Titan",
        option2: "Colossal Titan",
        option3: "Attack Titan",
        option4: "Beast Titan",
        answer: "Attack Titan",
    },
    {
        id: 36,
        question: "In 'Attack on Titan', Which branch of the military does Mikasa join?",
        option1: "None",
        option2: "Military Police Brigade",
        option3: "Garrison Regiment",
        option4:"Scout Regiment",
        answer: "Scout Regiment",
    },
    {
        id: 37,
        question: "In 'Attack on Titan', What does Annie do when she is captured?",
        option1: "Crystallizes",
        option2: "Kills Herself",
        option3: "Leaks Information",
        option4: "Escapes",
        answer: "Crystallizes",
    },
    {
        id: 38,
        question: "In 'Attack on Titan', Who finds out Annie is the Female Titan?",
        option1: "Levi",
        option2: "Armin",
        option3: "Eren",
        option4: "Mikasa",
        answer: "Armin",
    },
    {
        id: 39,
        question: "In 'Attack on Titan', Who seals the hole in Wall Rose?",
        option1: "Levi",
        option2: "Armin",
        option3: "Eren",
        option4: "Mikasa",
        answer: "Eren",
    },
    {
        id: 40,
        question: "In 'Naruto', Who was Naruto's teacher?",
        option1: "Jiraiya",
        option2: "Minato",
        option3: "Kakashi",
        option4:"Iruka",
        answer: "Iruka",
    },
    {
        id: 41,
        question: "In 'Naruto', Which of these is NOT a member of the Nara clan?",
        option1: "Jiraiya",
        option2: "Yoshino",
        option3: "Ensui",
        option4:"Shikaku",
        answer: "Jiraiya",
    },
    {
        id: 42,
        question: "In 'Naruto', Which of these people has been Hokage the most?",
        option1: "Tsunade",
        option2: "Hiruzen Sarutobi",
        option3: "Kakashi Hatake",
        option4: "Hashirama Senju",
        answer: "Hiruzen Sarutobi",
    },
    {
        id: 43,
        question: "In 'Naruto', Which famed clan was completely massacred?",
        option1: "Hyuuga",
        option2: "Nara",
        option3: "Uchiha",
        option4:"Uzumaki",
        answer: "Uchiha",
    },
    {
        id: 44,
        question: "In 'Naruto', Which of these is NOT one of Naruto's specialties?",
        option1: "Shadow clone jutsu",
        option2: "Rasengun",
        option3: "Sexy Jutsu",
        option4:"Chidori",
        answer: "Chidori",
    },
    {
        id: 45,
        question: "In 'Naruto', What is Tsunade's 'drug'?",
        option1: "Gambling",
        option2: "Alcohol",
        option3: "Men",
        option4:"Work",
        answer: "Gambling",
    },
    {
        id: 46,
        question: "In 'Naruto', Which friend of Naruto's died during the Fourth Great War?",
        option1: "Sasuke",
        option2: "Neji",
        option3: "Rock Lee",
        option4: "Gaara",
        answer: "Neji",
    },
    {
        id: 47,
        question: "In 'Naruto', Which ninja cannot do ninjutsu?",
        option1: "Sasuke",
        option2: "Neji",
        option3: "Rock Lee",
        option4:"Gaara",
        answer: "Rock Lee",
    },
    {
        id: 48,
        question: "In 'Naruto', Who does Naruto eventually marry?",
        option1: "Kaguya",
        option2: "Tsunade",
        option3: "Sakura",
        option4:"Hinata",
        answer: "Hinata",
    },
    {
        id: 49,
        question: "In 'Naruto', What is Team Asuma's favorite food?",
        option1: "BBQ",
        option2: "Ramen",
        option3: "Sushi",
        option4: "Taiyaki",
        answer: "BBQ",
    }
]

const HardQuestions = [
    {
        id: 0,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 1,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 2,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 3,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 4,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 5,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 6,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 7,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 8,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 9,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 10,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 11,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 12,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 13,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 14,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 15,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 16,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 17,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 18,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 19,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 20,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 21,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 22,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 23,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 24,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 25,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 26,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 27,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 28,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 29,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 30,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 31,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 32,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 33,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 34,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 35,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 36,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 37,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 38,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 39,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 40,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 41,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 42,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 43,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 44,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 45,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 46,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 47,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 48,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 49,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    }
]
export {Questions, MediumQuestions, HardQuestions}