const Questions = [
    {
        id: 0,
        question: "What is a hotdog?",
        option1: "a sandwich",
        option2: "a burger",
        option3: "a pizza",
        option4:"a fruit",
        answer: "a sandwich",
    },
    {
        id: 1,
        question: "What is yellow?",
        option1: "food",
        option2: "drink",
        option3: "color",
        option4:"car",
        answer: "color",
    },
    {
        id: 2,
        question: "What is a lemon?",
        option1: "animal",
        option2: "color",
        option3: "car",
        option4:"fruit",
        answer: "fruit",
    },
    {
        id: 3,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 4,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 5,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 6,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 7,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 8,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    {
        id: 9,
        question: "",
        option1: "",
        option2: "",
        option3: "",
        option4:"",
        answer: "",
    },
    
]

export default Questions;